spring.datasource.url=jdbc:postgresql://ep-snowy-art-aqsk86vq-pooler.c-8.us-east-1.aws.neon.tech/porfolio?sslmode=require&channelBinding=require
spring.datasource.username=neondb_owner
spring.datasource.password=npg_mYVI6Tr1CJgQ
spring.datasource.hikari.maximun-pool-size=10
spring.datasource.hikari.connection-time-out=20000

spring.sql.init.mode=always